"""User ORM model — uid sourced from Backend, never generated by Agent."""

from sqlalchemy import Column, String, Integer, JSON, TIMESTAMP, func
from sqlalchemy.orm import relationship

from app.database import Base


class User(Base):
    """
    Represents an authenticated Kairos user.
    The uid is provided by the Backend (UUID v4, stored as string).
    Allergy data is stored separately from preferences for safety isolation.
    """

    __tablename__ = "users"

    uid = Column(String(36), primary_key=True)

    # Rich preference snapshot updated by background profiler
    preferences = Column(JSON, nullable=False, default=dict)

    # SAFETY-CRITICAL: never inferred from chat
    allergies = Column(JSON, nullable=False, default=dict)

    # Denormalised flat lists
    allergy_flags = Column(JSON, nullable=False, default=list)
    dietary_flags = Column(JSON, nullable=False, default=list)
    vibe_tags = Column(JSON, nullable=False, default=list)
    preferred_price_tiers = Column(JSON, nullable=False, default=list)

    # Lifecycle
    interaction_count = Column(Integer, nullable=False, server_default="0")
    last_active_at = Column(TIMESTAMP(timezone=True), nullable=True)
    created_at = Column(
        TIMESTAMP(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at = Column(
        TIMESTAMP(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )

    # Relationships
    interactions = relationship(
        "Interaction", back_populates="user", cascade="all, delete-orphan"
    )
