"""User ORM model — uid sourced from Backend, never generated by Agent."""

from sqlalchemy import Column, String, Integer, ARRAY, TIMESTAMP, func
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import relationship

from app.database import Base


class User(Base):
    """
    Represents an authenticated Kairos user.
    The uid is provided by the Backend (UUID v4).
    Allergy data is stored separately from preferences for safety isolation.
    """

    __tablename__ = "users"

    uid = Column(UUID(as_uuid=True), primary_key=True)

    # Rich preference snapshot updated by background profiler
    preferences = Column(JSONB, nullable=False, server_default="{}")

    # SAFETY-CRITICAL: never inferred from chat
    allergies = Column(JSONB, nullable=False, server_default="{}")

    # Denormalised flat lists for fast GIN queries
    allergy_flags = Column(ARRAY(String), nullable=False, server_default="{}")
    dietary_flags = Column(ARRAY(String), nullable=False, server_default="{}")
    vibe_tags = Column(ARRAY(String), nullable=False, server_default="{}")
    preferred_price_tiers = Column(ARRAY(String), nullable=False, server_default="{}")

    # Lifecycle
    interaction_count = Column(Integer, nullable=False, server_default="0")
    last_active_at = Column(TIMESTAMP(timezone=True), nullable=True)
    created_at = Column(
        TIMESTAMP(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at = Column(
        TIMESTAMP(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )

    # Relationships
    interactions = relationship(
        "Interaction", back_populates="user", cascade="all, delete-orphan"
    )
