"""
ChromaDB client — singleton PersistentClient and reviews collection.
Embeddings generated by Google text-embedding-004 are stored here for
cosine-similarity search in the hybrid_search service.
"""

from __future__ import annotations

import chromadb

from app.config import settings

_client: chromadb.ClientAPI | None = None
_collection: chromadb.Collection | None = None


def get_chroma_client() -> chromadb.ClientAPI:
    """Return (or lazily create) the singleton ChromaDB PersistentClient."""
    global _client
    if _client is None:
        _client = chromadb.PersistentClient(path=settings.chroma_path)
    return _client


def get_reviews_collection() -> chromadb.Collection:
    """Return (or lazily create) the 'reviews' collection with cosine space."""
    global _collection
    if _collection is None:
        client = get_chroma_client()
        _collection = client.get_or_create_collection(
            name="reviews",
            metadata={"hnsw:space": "cosine"},
        )
    return _collection
